-- Remises sur devis et factures (montant FCFA ou pourcentage)
ALTER TABLE "Devis" ADD COLUMN IF NOT EXISTS "remiseMontant" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Devis" ADD COLUMN IF NOT EXISTS "remisePourcent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Facture" ADD COLUMN IF NOT EXISTS "remiseMontant" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Facture" ADD COLUMN IF NOT EXISTS "remisePourcent" DOUBLE PRECISION NOT NULL DEFAULT 0;
